const adminMenu = [
    {
        route:"/home/dashboard",
        name:"Dashboard",
        title:"系统首页",
        type:"view",
        icon:"el-icon-menu",
        filePath:"page/home/dashboard/index",
        order:null,
        isNav:true,
        
    },
    {
        route:null,
        name:"UserAbout",
        title:"用户相关",
        type:"folder",
        icon:"el-icon-s-custom",
        filePath:"",
        order:null,
        isNav:true,
        children:[
            {
                route:"/user/list",
                name:"UserList",
                title:"用户管理",
                type:"view",
                icon:"el-icon-setting",
                filePath:"page/home/user/userList",
                order:null,
                isNav:true
            }
        ]
    },
    {
        route:null,
        name:"Classic",
        title:"classic管理",
        type:"folder",
        icon:"el-icon-film",
        filePath:null,
        order:null,
        isNav:true,
        children:[
            {
                route:"/classic/list",
                name:"ClassicList",
                title:"classic列表",
                type:"view",
                icon:"el-icon-s-operation",
                filePath:"page/home/classic/classicList",
                order:null,
                isNav:true
            },
            {
                route:"/classic/detail",
                name:"ClassicDetail",
                title:"classic详情",
                type:"view",
                icon:"",
                filePath:"page/home/classic/classicDetail",
                order:null,
                isNav:false
            },
            {
                route:"/classic/add",
                name:"ClassicAdd",
                title:"classic发布",
                type:"view",
                icon:"el-icon-edit-outline",
                filePath:"page/home/classic/classicAdd",
                order:null,
                isNav:true
            }
        ]
    }
]

export default adminMenu